### ISSUE TITLE
Refactor code to use generics

### ISSUE THREAD

**Issue by kkoreilly** [goki/ki#11]
A lot of code (like that in package ints) could be made much faster and cleaner by using generics.

**Comment by rcoreilly** [comment]
Here's the only way to write a generic New method without relying on reflect, when you have fully generic `any` objects stored in a type registry:

```Go
func New[T any](t T) T {
	switch any(t).(type) {
	case *gi.TabView:
		v := new(gi.TabView)
		return any(v).(T)
	}
	return any(nil).(T)
}

	bbb := New(any(tv))
	fmt.Printf("%#v\n", bbb)
```

We couldn't find any way to get around the type switch.

You could have a generator that generates the equivalent of our existing `Clone` method, that uses the actual type.  This could return the actual type or the Ki type:

```Go
func (b *Button) Clone() ki.Ki {
    return new(Button)
}
```

**Comment by rcoreilly** [comment]
The key constraint for *why* you need a type switch in the above `New` function is that there is no "value" representation of type (outside of reflect) -- with a type switch, the compiler has the concrete target "case" type and the actual object, and can generate the necessary code to see if it is that thing, but it can't just take the type "value" itself and pass it along to something else.  That would require all the complexity of representing types that is present in reflect, which is the point of why reflect is slow and complicated -- type values can be quite complicated.

Metaphorically, it is much easier to build a bridge between two specific points than it is to build something that will take you anywhere you want to go..

**Comment by rcoreilly** [comment]
done.
