### ISSUE TITLE
Incorrect initialization order of Ki fields

### ISSUE THREAD

**Issue by kkoreilly** [goki/ki#15]
Currently, any Ki fields for a node are initialized and inserted before the node itself is inserted. For example, suppose you have a node called A. You initialize node A with `InitNode` and then add a child, node B, who has a field node C (such that the full path of node C should be `A/B.C`). `AddNewChild` calls `InitNode` on node B, which calls `InitNode` and `SetParent` on node C as part of the Ki fields logic. However, `SetParent` has not yet been called on node B, as the initialization of Ki fields (such as node C) happens before the setting of the parent. Therefore, `OnAdd` is called for node C before it is called for node B, despite node B being higher in the tree. This means that, despite being in `OnAdd`, in which you expect to have your parents defined, node C has a parent without a name or parents. Node C has no way to know what its grandparents or other extended parents are, as the tree ends at node B. Furthermore, calling `Path` on node C results in `/.C`, when it should result in `A/B.C`.

**Comment by kkoreilly** [comment]
The problem with resolving this issue is that there is no other guaranteed place to initialize struct fields, as a node could be the root node and therefore never get added to a parent.

**Comment by rcoreilly** [comment]
Ki fields have been removed. Much cleaner.  Parts now working well in gogi.
