### ISSUE TITLE
missing dirs.AllFiles() and dirs.HasFile()

### ISSUE THREAD

**Issue by xvalen** [goki/ki#4]
I am not able to compile examples of goki and after same searching I have found that dirs.AllFiles() and dirs.HasFile() are missing in my:

~/go/pkg/mod/github.com/goki/ki@v0.9.10/dirs/dirs.go

in ~/go/src/github.com/goki/ki/dirs/dirs.go both functions are available.

I am just learning the go language so I dont know what happend.

Even if I delete package (and files from pkg/mod directory) and install it again with go get ...it comes to same state.

What I am doing wrong please?

Here is example code:
`package main

import (
	"fmt"

	"github.com/goki/ki/dirs"
)

func main() {

	fmt.Println(dirs.GoSrcDir("."))

	// does not work with:
	// undefined: dirs.AllFiles [15,13]
	// err, xs := dirs.AllFiles("")
}`

Thank you.
Petr

**Comment by rcoreilly** [comment]
do `export GO111MODULES=off` and then re-do the install instructions

it is pulling the older version of ki and gi requires a newer version but I haven't yet updated all the modules b/c I'm just in the process of finalizing a 1.0 release..

**Comment by xvalen** [comment]
Thank you!

**Comment by rcoreilly** [comment]
I updated install instructions with more info about this.  closing this ticket.
